---
title: "super simple schema"
author: "BBL"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(dplyr)
library(DT)
```

## Read the data

The **plot table** provides treatment/plot/individual information based on `design_link`.

```{r}
plot_data <- read_csv("plot_names.csv", show_col_types = FALSE)
datatable(plot_data) %>% 
    formatStyle("design_link", color = "red") %>% 
    formatStyle("logger", color = "green")
```

The **design table** links logger variables with their design (as specified in the plot table).

```{r}
design_data <- read_csv("design_document.csv", show_col_types = FALSE)
datatable(design_data) %>%
    formatStyle("design_link", color = "red") %>%
    formatStyle("loggernet_variable", color = "blue")
```

The **logger data table** is downloaded from the logger. 

```{r}
logger_data <- read_csv("logger_data.csv", show_col_types = FALSE)
datatable(logger_data) %>%
    formatStyle("logger", color = "green")
```

## Reshape logger data and join with design info

```{r}
logger_data %>% 
    pivot_longer(c(-logger, -timestamp), names_to = "loggernet_variable") %>%
    left_join(select(design_data, loggernet_variable, design_link, research_name),
              by = "loggernet_variable") ->
    dat1
datatable(dat1)
```

## Join with plot data

```{r}
dat1 %>% 
    left_join(plot_data, by = c("logger", "design_link")) ->
    dat2
datatable(dat2)
```

## Reshape for final output

```{r}
dat2 %>% 
    select(-design_link, -loggernet_variable) %>% 
    pivot_wider(names_from = "research_name", values_from = "value") %>% 
    datatable()
```

## A little test

```{r, include=FALSE}

PATTERN <- "([[:alnum:]]+,)+[[:alnum:]]+"
expand_string <- function(s) {
    matches <- regexpr(PATTERN, s)
    
    if(matches > 0) {
        subs <- strsplit(regmatches(s, matches), ",")[[1]]
        s <- rep(s, length(subs))
        newmatches <- regexpr(PATTERN, s)
        regmatches(s, newmatches) <- subs
    }
    s
}

test <- tribble(~x,               ~y,          ~comment,
                "sapflux(1)",     "y1",        "no expansion",
                "sapflux(2,3)",   "y2a,y2b",   "x and y both expand",
                "logger",         "y3a,y3b",   "y expands, x replicates",
                "logger,S11,S12", "y4",        "x expands, y replicates")

results <- list()
for(i in seq_len(nrow(test))) {
    df <- test[i,]  # row we're working on
    # Figure out max expansion (may be 1) and replicate row that many times
    expand_lens <- sapply(df, function(x) length(expand_string(x)))
    df <- df[rep(1, max(expand_lens)),]
    # For each column, expand its entry string as needed 
    for(col in seq_len(ncol(df))) {
        df[col] <- expand_string(unlist(df[1,col]))
    }    
    results[[i]] <- df
}

bind_rows(results)
```

